[package]
name = "showcase"
version = "0.1.0"
edition = "2021"
authors = ["Flavio Bizzarri <fl.bizzarri@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/newfla/egui-theme-switcher"

[dependencies]
eframe.workspace = true
egui-theme-switcher = { path = "../../"}
